"""Test the §24 validation_engine.py against three real sources in this
codebase, and produce a results report.

  SOURCE A -- address_vendor_lines.yaml (20 real industrial vendor addresses,
              hand-authored expectations, multiline convention). For each
              case: run the PRODUCTION resolve_address_blob (the real
              system this validation engine is designed to wrap), then run
              the candidate through validate(). Compare verdict against
              whether resolve_address_blob's own output matched the hand-
              written expectation (known from the existing eval harness).

  SOURCE B -- address_holdout_cases.yaml (30 frozen held-out cases, never
              tuned against -- see docs/ADDRESS_SEGMENTATION_RESEARCH.md
              §12/§23 for why this matters: a fair test needs cases the
              validation engine's own thresholds were not shaped by).

  SOURCE C -- 2,000-row random sample of the 100k-row Excel corpus this
              research is built on, comparing the PRODUCTION segmenter's
              output against the Excel ground truth via a REFERENCE
              candidate cross-check (Step 5), since the Excel ground truth
              itself is NOT a reliable target (§4/§12 of the report) -- this
              tests the validation engine's DISAGREEMENT DETECTION, not
              "does it match the Excel file," which the report already
              proved is the wrong question.

  SOURCE D -- deliberately corrupted variants of Source A (missing token,
              reordered, PIN changed, boundary shift vs reference) to
              confirm the hard-fail gates actually fire on real address
              text, not just the synthetic toy strings in the sanity check.

Output: research/address_segmentation_boundary/output/validation_report.md
"""
from __future__ import annotations

import pathlib
import random
import sys

import pandas as pd
import yaml

sys.path.insert(0, r"C:\Users\shubh\Downloads\vendor-extractor\backend")
from app.services.extraction_pipeline.extract.address_resolver import resolve_address_blob  # noqa: E402

from load_data import load_partition  # noqa: E402
from validation_engine import validate  # noqa: E402

random.seed(42)
ROOT = pathlib.Path(r"C:\Users\shubh\Downloads\vendor-extractor")
OUT = ROOT / "research" / "address_segmentation_boundary" / "output"
OUT.mkdir(exist_ok=True)

lines = []


def log(*a):
    s = " ".join(str(x) for x in a)
    print(s)
    lines.append(s)


def md_table(rows: list[dict], cols: list[str]) -> str:
    out = ["| " + " | ".join(cols) + " |", "|" + "|".join(["---"] * len(cols)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(r.get(c, "")) for c in cols) + " |")
    return "\n".join(out)


# ===========================================================================
log("# Validation Engine (§24) -- Results Report\n")
log("Generated by `research/address_segmentation_boundary/scripts/run_validation_report.py`.")
log("Tests the isolated experimental implementation of the report's §24 algorithm against")
log("real data in this codebase. No production code was modified to produce this report.\n")

# ---------------------------------------------------------------------------
log("## Source A -- 20 real industrial vendor addresses (`address_vendor_lines.yaml`)\n")
log("For each: production `resolve_address_blob(multiline=True)` produces the candidate,")
log("the SAME candidate is fed through `validate()`, and the verdict is compared against")
log("whether production's own output matched the hand-authored expectation.\n")

with open(ROOT / "backend" / "app" / "eval" / "address_vendor_lines.yaml", encoding="utf-8") as f:
    vendor_cases = yaml.safe_load(f)["cases"]

a_rows = []
a_verdict_counts = {"ACCEPT": 0, "REVIEW": 0, "REJECT": 0}
a_confusion = {"expect_match_verdict": {}, "expect_mismatch_verdict": {}}
for c in vendor_cases:
    res = resolve_address_blob(c["address"], multiline=True)
    expect = c["expect"]
    expect_matched = (
        res.address_1 == expect.get("address_1", "")
        and res.address_2 == expect.get("address_2", "")
        and res.address_3 == expect.get("address_3", "")
    )
    v = validate(c["address"], res.address_1, res.address_2, res.address_3, res.address_4,
                 candidate_source="rule_engine",
                 candidate_city=res.city, candidate_state=res.state, candidate_pin=res.pin_code)
    a_verdict_counts[v.verdict] += 1
    bucket = a_confusion["expect_match_verdict"] if expect_matched else a_confusion["expect_mismatch_verdict"]
    bucket[v.verdict] = bucket.get(v.verdict, 0) + 1
    a_rows.append({
        "id": c["id"], "expect_matched": expect_matched, "verdict": v.verdict,
        "plausibility": v.structural_plausibility, "gap": round(v.gap_strength, 2) if v.gap_strength is not None else "",
        "hard_fail": v.hard_fail_reason or "",
    })

log(md_table(a_rows, ["id", "expect_matched", "verdict", "plausibility", "gap", "hard_fail"]))
log(f"\nVerdict counts: {a_verdict_counts}")
log(f"Verdict breakdown WHEN production matched the hand-written expectation: {a_confusion['expect_match_verdict']}")
log(f"Verdict breakdown WHEN production did NOT match the expectation:       {a_confusion['expect_mismatch_verdict']}")
log("")

# ---------------------------------------------------------------------------
log("## Source B -- 30 frozen held-out addresses (`address_holdout_cases.yaml`)\n")
log("These were authored to measure generalization and have never been tuned against by")
log("either the production segmenter or this validation engine.\n")

with open(ROOT / "backend" / "app" / "eval" / "address_holdout_cases.yaml", encoding="utf-8") as f:
    holdout_cases = yaml.safe_load(f)["cases"]

b_rows = []
b_verdict_counts = {"ACCEPT": 0, "REVIEW": 0, "REJECT": 0}
b_confusion = {"expect_match_verdict": {}, "expect_mismatch_verdict": {}}
for c in holdout_cases:
    res = resolve_address_blob(c["address"], multiline=True)
    expect = c["expect"]
    expect_matched = (
        res.address_1 == expect.get("address_1", "")
        and res.address_2 == expect.get("address_2", "")
        and res.address_3 == expect.get("address_3", "")
    )
    v = validate(c["address"], res.address_1, res.address_2, res.address_3, res.address_4,
                 candidate_source="rule_engine",
                 candidate_city=res.city, candidate_state=res.state, candidate_pin=res.pin_code)
    b_verdict_counts[v.verdict] += 1
    bucket = b_confusion["expect_match_verdict"] if expect_matched else b_confusion["expect_mismatch_verdict"]
    bucket[v.verdict] = bucket.get(v.verdict, 0) + 1
    b_rows.append({
        "id": c["id"], "expect_matched": expect_matched, "verdict": v.verdict,
        "plausibility": v.structural_plausibility, "gap": round(v.gap_strength, 2) if v.gap_strength is not None else "",
        "hard_fail": v.hard_fail_reason or "",
    })

log(md_table(b_rows, ["id", "expect_matched", "verdict", "plausibility", "gap", "hard_fail"]))
log(f"\nVerdict counts: {b_verdict_counts}")
log(f"Verdict breakdown WHEN production matched the hand-written expectation: {b_confusion['expect_match_verdict']}")
log(f"Verdict breakdown WHEN production did NOT match the expectation:       {b_confusion['expect_mismatch_verdict']}")
log("")

# ---------------------------------------------------------------------------
log("## Source C -- 2,000-row sample of the 100k Excel corpus: disagreement detection\n")
log("The Excel ground truth's own split_index is NOT used as a target (see report §4/§12 --")
log("it is proven statistically independent of content). Instead, the production segmenter's")
log("candidate is validated, and the Excel file's address_1 is supplied as `reference_address_1`")
log("-- a genuine second, independently-produced (by a different generation process) opinion,")
log("which is exactly the situation Step 5 is designed for.\n")

part = load_partition()
sample = part.sample(n=2000, random_state=42).reset_index(drop=True)

c_verdict_counts = {"ACCEPT": 0, "REVIEW": 0, "REJECT": 0}
c_deciding_stage = {}
c_hard_fail_reasons = {}
c_review_reasons = {}
for _, r in sample.iterrows():
    res = resolve_address_blob(r["address"], multiline=True)
    v = validate(r["address"], res.address_1, res.address_2, res.address_3, res.address_4,
                 candidate_source="rule_engine", reference_address_1=r["address_1"],
                 candidate_city=res.city, candidate_state=res.state, candidate_pin=res.pin_code)
    c_verdict_counts[v.verdict] += 1
    c_deciding_stage[v.deciding_stage] = c_deciding_stage.get(v.deciding_stage, 0) + 1
    if v.hard_fail_reason:
        c_hard_fail_reasons[v.hard_fail_reason] = c_hard_fail_reasons.get(v.hard_fail_reason, 0) + 1
    if v.review_reason:
        c_review_reasons[v.review_reason] = c_review_reasons.get(v.review_reason, 0) + 1

log(f"n = {len(sample)}")
log(f"Verdict counts: {c_verdict_counts}")
log(f"Deciding stage counts: {c_deciding_stage}")
log(f"Hard-fail reasons: {c_hard_fail_reasons}")
log(f"Review reasons: {c_review_reasons}")
log("")
log("Interpretation: production's own reconstruction/order guarantees (I1/I3, already tested)")
log("mean Step 2 (hard-fail) essentially never fires on the segmenter's OWN output -- it is a")
log("gate against corrupted candidates (e.g. from an LLM), and the rule engine cannot produce")
log("a corrupted candidate by construction. The ACCEPT/REVIEW split at Step 4/5 is the")
log("meaningful number here: it measures how often the rule engine's chosen boundary looks")
log("structurally confident vs. how often it needs a human's attention, on a large, diverse,")
log("independently-generated address sample it was never tuned against.")
log("")

# ---------------------------------------------------------------------------
log("## Source D -- deliberately corrupted variants of Source A (hard-fail gate confirmation)\n")

d_rows = []


def word_tokens(s):
    return s.replace(",", " ,").split()


for c in vendor_cases[:8]:
    res = resolve_address_blob(c["address"], multiline=True)
    full = c["address"]

    fielded = dict(candidate_city=res.city, candidate_state=res.state, candidate_pin=res.pin_code)

    # missing token: drop the last word of address_2
    a2_words = res.address_2.split()
    if len(a2_words) >= 2:
        corrupted_a2 = " ".join(a2_words[:-1])
        v = validate(full, res.address_1, corrupted_a2, res.address_3, res.address_4, **fielded)
        d_rows.append({"id": c["id"], "corruption": "drop_last_token_of_address_2",
                        "verdict": v.verdict, "hard_fail": v.hard_fail_reason})

    # reordered: swap address_1 and address_2
    if res.address_2:
        v = validate(full, res.address_2, res.address_1, res.address_3, res.address_4, **fielded)
        d_rows.append({"id": c["id"], "corruption": "swap_address_1_and_2",
                        "verdict": v.verdict, "hard_fail": v.hard_fail_reason})

    # PIN changed, if this case has a 6-digit PIN anywhere in the source
    import re
    pins = re.findall(r"\b\d{6}\b", full)
    if pins:
        bad_pin = str(int(pins[0]) + 1).zfill(6)
        corrupted_full = full.replace(pins[0], bad_pin, 1)
        # candidate still claims the OLD (correct) pin was seen -- simulate an
        # LLM that silently "corrected" a digit
        v = validate(corrupted_full, res.address_1, res.address_2.replace(pins[0], pins[0]), res.address_3, res.address_4, **fielded)
        # here the corrupted full_address itself carries the new pin, and the
        # candidate lines were built from the OLD text -- a realistic
        # "candidate doesn't match a changed input" case
        d_rows.append({"id": c["id"], "corruption": "input_pin_changed_candidate_stale",
                        "verdict": v.verdict, "hard_fail": v.hard_fail_reason})

log(md_table(d_rows, ["id", "corruption", "verdict", "hard_fail"]))
log("")
log(f"REJECT rate on deliberately corrupted candidates: "
    f"{sum(1 for r in d_rows if r['verdict']=='REJECT')} / {len(d_rows)}")

# ===========================================================================
report_path = OUT / "validation_report.md"
report_path.write_text("\n".join(lines), encoding="utf-8")
print(f"\n\nWrote {report_path}")
